### ISSUE TITLE
Headers empty

### ISSUE THREAD

**Issue by janat08** [PropelAuth/cloudflare-worker#10]
```
UnauthorizedException [Error]: No authorization header found.
    at extractBearerToken (file:///C:/Users/user/Documents/classifieds/node_modules/@propelauth/cloudflare-worker/dist/index.mjs:2279:15)
    at file:///C:/Users/user/Documents/classifieds/node_modules/@propelauth/cloudflare-worker/dist/index.mjs:2273:29
    at Generator.next (<anonymous>)
    at fulfilled (file:///C:/Users/user/Documents/classifieds/node_modules/@propelauth/cloudflare-worker/dist/index.mjs:19:58) {
  status: 401
```
Im doing this with qwik framework and I get nothing in my headers. Im logged in on frontend and when navigating between pages or making api requests I get errors about empty headers.

**Comment by janat08** [comment]
Also tried just doing server side raw headers, empty even if logged in.
